### ISSUE TITLE
latest version of logstash-input-beats has unecessary files in vendor

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-beats#11]
this makes the 0.9.4 gem over 15mb instead of 24k

**Comment by ph** [comment]
I think  you have the wrong version.. 0.9.3 was released today and it fixes this issue.

<img width="262" alt="screenshot 2015-10-29 12 01 07" src="https://cloud.githubusercontent.com/assets/640/10824010/c216f880-7e34-11e5-8e94-a18bef93901b.png">
