### ISSUE TITLE
Error on second connection

### ISSUE THREAD

**Issue by tsg** [logstash-plugins/logstash-input-beats#115]
Version: LS 5.0.0-alpha5 (RC) Beats plugin:  3.1.0.beta3
Operating System: Ubuntu 12.04 (32 bits)
Java version: 1.8.0_101
Using the tar.gz

Steps to Reproduce:

* Start Logstash with the following:

```
./bin/logstash -e 'input { beats { port => 5044 } } output { stdout { codec => dots } }'
```

* Start Filebeat with the following config:

```
filebeat.prospectors:
- input_type: log
  paths:
    - /home/vagrant/test.log

filebeat.registry: /home/vagrant/data/registry.json

output.logstash:
  hosts: ["192.168.33.72:5044"]
```

The `test.log` file just has a few lines in it:

```
test1
test2
test3
```

* Dots should be printed
* Kill filebeat (^C) before finishing the file
* Delete the registry file and restart Filebeat

Now Filebeat fails to establish a connection with Logstash:

```
2016/08/03 15:44:56.162433 sync.go:85: ERR Failed to publish events caused by: read tcp 192.168.33.74:50216->192.168.33.72:5044: read: connection reset by peer
2016/08/03 15:44:56.162465 single.go:91: INFO Error publishing events (retrying): read tcp 192.168.33.74:50216->192.168.33.72:5044: read: connection reset by peer
2016/08/03 15:44:57.164493 sync.go:85: ERR Failed to publish events caused by: read tcp 192.168.33.74:50217->192.168.33.72:5044: read: connection reset by peer
```

**Comment by ph** [comment]
This was an issue with b3, I have fixed it in b4.

Related issues: https://github.com/logstash-plugins/logstash-input-beats/pull/112

**Comment by tsg** [comment]
I can confirm that it's fixed in beta4. Thanks, @ph ❤️
