### ISSUE TITLE
Multiline codec can't differentiate different sources

### ISSUE THREAD

**Issue by acchen97** [logstash-plugins/logstash-input-beats#13]
Currently the Beats input doesn't natively support multiline events from multiple different streams. As multiline codec is the thread safe option, this should be fixed accordingly.

Same issue as in the file input: logstash-plugins/logstash-input-file#44

**Comment by ph** [comment]
Some initial work done in https://github.com/elastic/logstash/pull/4104

**Comment by ph** [comment]
#22 implement most of the logic, #23 need to be resolved for buffered contents will do in another PR.

**Comment by ph** [comment]
released logstash-input-beats 2.0.0 and only support logstash 2.0.0 and require logstash-codec-multiline 2.0.3
