### ISSUE TITLE
Install offline

### ISSUE THREAD

**Issue by mrjameshamilton** [logstash-plugins/logstash-input-beats#140]
When I try to install offline - with pack on a machine with internet connection, or by building the gem from source, it still tries to connect to rubygems.org and fails.

Installing logstash-input-beats
Error Bundler::HTTPError, retrying 1/10
Could not fetch specs from https://rubygems.org/

How can I install it on a machine without an internet connection?

**Comment by ph** [comment]
To do an airgap/offline installation you will have to use the `pack` command, this page should help you go through this process.

https://www.elastic.co/guide/en/logstash/current/offline-plugins.html

**Comment by mrjameshamilton** [comment]
I did exactly that and still get the error

**Comment by acchen97** [comment]
@mrjameshamilton there are known issues with the offline plugin installation workflow today, see https://github.com/elastic/logstash/issues/5906.

As a stop gap solution, you could stage your LS directory on an online box (install/update all plugins required) then package+ship it to your offline boxes.

**Comment by jordansissel** [comment]
The problem is with the plugin manager, not the beats input. Let's redirect discussion for this over to this ticket: https://github.com/elastic/logstash/issues/4651
