### ISSUE TITLE
bug: ssl_certificate_authorities setting only loads the first certificate in each file.

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-beats#153]
Buggy code linked here: https://github.com/logstash-plugins/logstash-input-beats/blob/776f05ce52111d39e394798428598abfd4dbbf68/src/main/java/org/logstash/netty/SslSimpleBuilder.java#L152

```
in = new FileInputStream(certificate);
collections[i] = (X509Certificate) certificateFactory.generateCertificate(in);
```

CertificateFactory.generateCertificate(...) only returns a single X509Certificate. However, a single file can contain multiple certificates.

Fix: Use CertificateFactory.generateCertificates(...) (the plural method name) which returns an array of X509Certificate.

**Comment by ph** [comment]
lets make sure we also update the doc to reflect that changes.

This sentence under the **certificates_authorities** need to be removed.

> This feature only supports certificates that are directly signed by your root CA. Intermediate CA are currently not supported.
