### ISSUE TITLE
logstash v5.0.1 cipher not available

### ISSUE THREAD

**Issue by rauizab** [logstash-plugins/logstash-input-beats#159]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: 5.0.1
- Operating System: Centos 7
- Config File (if you have sensitive info, please remove it): 
- Sample Data:
- Steps to Reproduce: On start

Hi 
With v5.0.0 logstash works, but with version v5.0.1 I get "cipher X not available".
I have tried:
* without  cipher_suites
* with ciphers from https://github.com/logstash-plugins/logstash-input-beats/blob/master/src/main/java/org/logstash/netty/SslSimpleBuilder.java "DEFAULT_CIPHERS",
* with ciphers from https://wiki.mozilla.org/Security/Server_Side_TLS

Logstash.conf
> input {
>   beats {
>     port => 5044
>     ssl => true
>     ssl_certificate => "/logstash/logstash.crt"
>     ssl_key => "/logstash/logstash.key"
>     cipher_suites => "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
>   }
> }

What am I doing wrong?

Best regards

**Comment by jordansissel** [comment]
Can you attach your beats configuration as well?

**Comment by rauizab** [comment]
My filebeat is
> output:
>  logstash:
>   hosts: ["logstash.hostname:5044"]
>  timeout: 15
> ssl.certificate_authorities: ["/filebeat/logstash.crt"]
>  console:
>    pretty: true
>
> filebeat.prospectors:
> -
> paths:
> ...

**Comment by jordansissel** [comment]
What version of Java? (`java -version`)

**Comment by rauizab** [comment]
openjdk version "1.8.0_92-internal"
OpenJDK Runtime Environment (build 1.8.0_92-internal-alpine-r1-b14)
OpenJDK 64-Bit Server VM (build 25.92-b14, mixed mode)

**Comment by untergeek** [comment]
> "1.8.0_92-internal"

Internal?  As in, it's a custom build of the OpenJDK?  If true, that might have something to do with it.

**Comment by jordansissel** [comment]
My hypothesis is that one of two things is happening.  These are speculation that require testing to validate:

1) Maybe: Your java build is custom and doesn't have support for ciphers that beats offers.
2) or, Maybe: your ssl certificate somehow is causing an SSL negotation that is preventing normally-working ciphers from working. This is a rare problem I have never seen in production.

**Comment by rauizab** [comment]
I will try with another java version. I can close the ticket and open it again if a find the problem again.
Do you have a java version recommendation?
Anyway, just to mention that with version 5.0.0 it was working and with 5.0.1 not.

**Comment by vad** [comment]
same problem here on Ubuntu 14.04, solved removing the system OpenJDK (1.7). Oracle JDK (1.8) was the default but apparently OpenJDK breaks something even in that case.

**Comment by clemh78** [comment]
Same problem (https://discuss.elastic.co/t/problem-with-cipher-in-beat-input/67841) on Red hat 6.7. @rauizab you have found a solution ?

**Comment by rauizab** [comment]
Still I was not able to do it.
I tried with:
* installing version 5.0.2 of filebeats and logstash
* installing java version 1.8.0_111-internal
* I listed java ciphers available following: https://confluence.atlassian.com/stashkb/list-ciphers-used-by-jvm-679609085.html . List (my cipher is included):

`Default	Cipher 	
*	SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA
 	SSL_DHE_DSS_WITH_DES_CBC_SHA
 	SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA
*	SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA
 	SSL_DHE_RSA_WITH_DES_CBC_SHA
 	SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA
 	SSL_DH_anon_WITH_3DES_EDE_CBC_SHA
 	SSL_DH_anon_WITH_DES_CBC_SHA
 	SSL_RSA_EXPORT_WITH_DES40_CBC_SHA
*	SSL_RSA_WITH_3DES_EDE_CBC_SHA
 	SSL_RSA_WITH_DES_CBC_SHA
 	SSL_RSA_WITH_NULL_MD5
 	SSL_RSA_WITH_NULL_SHA
*	TLS_DHE_DSS_WITH_AES_128_CBC_SHA
*	TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
*	TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
*	TLS_DHE_DSS_WITH_AES_256_CBC_SHA
*	TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
*	TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
*	TLS_DHE_RSA_WITH_AES_128_CBC_SHA
*	TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
*	TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
*	TLS_DHE_RSA_WITH_AES_256_CBC_SHA
*	TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
*	TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
 	TLS_DH_anon_WITH_AES_128_CBC_SHA
 	TLS_DH_anon_WITH_AES_128_CBC_SHA256
 	TLS_DH_anon_WITH_AES_128_GCM_SHA256
 	TLS_DH_anon_WITH_AES_256_CBC_SHA
 	TLS_DH_anon_WITH_AES_256_CBC_SHA256
 	TLS_DH_anon_WITH_AES_256_GCM_SHA384
*	TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
*	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
*	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
*	TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
*	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
*	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
*	TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
 	TLS_ECDHE_ECDSA_WITH_NULL_SHA
*	TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
*	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
*	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
*	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
*	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
*	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
*	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
 	TLS_ECDHE_RSA_WITH_NULL_SHA
*	TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA
*	TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
*	TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
*	TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
*	TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
*	TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
*	TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
 	TLS_ECDH_ECDSA_WITH_NULL_SHA
*	TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA
*	TLS_ECDH_RSA_WITH_AES_128_CBC_SHA
*	TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
*	TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
*	TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
*	TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
*	TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
 	TLS_ECDH_RSA_WITH_NULL_SHA
 	TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA
 	TLS_ECDH_anon_WITH_AES_128_CBC_SHA
 	TLS_ECDH_anon_WITH_AES_256_CBC_SHA
 	TLS_ECDH_anon_WITH_NULL_SHA
*	TLS_EMPTY_RENEGOTIATION_INFO_SCSV
 	TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5
 	TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA
 	TLS_KRB5_WITH_3DES_EDE_CBC_MD5
 	TLS_KRB5_WITH_3DES_EDE_CBC_SHA
 	TLS_KRB5_WITH_DES_CBC_MD5
 	TLS_KRB5_WITH_DES_CBC_SHA
*	TLS_RSA_WITH_AES_128_CBC_SHA
*	TLS_RSA_WITH_AES_128_CBC_SHA256
*	TLS_RSA_WITH_AES_128_GCM_SHA256
*	TLS_RSA_WITH_AES_256_CBC_SHA
*	TLS_RSA_WITH_AES_256_CBC_SHA256
*	TLS_RSA_WITH_AES_256_GCM_SHA384
 	TLS_RSA_WITH_NULL_SHA256
`

I have to use still the logstash version 5.0.0 to make it work.

**Comment by rauizab** [comment]
Maybe this is related. They look similar:
https://github.com/elastic/logstash/issues/6121

**Comment by rauizab** [comment]
Tried with v5.1.1. Same result.

**Comment by rauizab** [comment]
Related to https://discuss.elastic.co/t/problem-with-cipher-in-beat-input/67841

**Comment by clemh78** [comment]
jess_571 has explain a solution in this topic : [https://discuss.elastic.co/t/problem-with-cipher-in-beat-input/67841/5](https://discuss.elastic.co/t/problem-with-cipher-in-beat-input/67841/5)

**Comment by rauizab** [comment]
I added to jvm.options but still getting the same error:
-Dio.netty.native.workdir=/logstash/temp
-Djava.io.tmpdir=/logstash/temp

**Comment by rauizab** [comment]
Anyone was able to make it running with docker?

**Comment by rauizab** [comment]
On trace I see:
[2016-12-16T13:39:49,657][DEBUG][io.netty.util.internal.logging.InternalLoggerFactory] Using Log4J as the default logging framework
[2016-12-16T13:39:49,669][DEBUG][io.netty.util.internal.NativeLibraryLoader] -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
[2016-12-16T13:39:49,669][DEBUG][io.netty.util.internal.NativeLibraryLoader] -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
[2016-12-16T13:39:49,693][DEBUG][io.netty.util.internal.NativeLibraryLoader] Unable to load the library: netty-tcnative-linux-x86_64.
java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative-linux-x86_644199097077208470722.so: Error loading shared library libcrypt.so.1: No such file or directory (needed by /tmp/libnetty-tcnative-linux-x86_644199097077208470722.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_111-internal]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_111-internal]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_111-internal]

I will close the bug as it seems that it is fixed. It is just that I was not able to set it up properly in my environment.

**Comment by jordansissel** [comment]
> java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative-linux-x86_644199097077208470722.so: Error loading shared library libcrypt.so.1: No such file or directory (needed by /tmp/libnetty-tcnative-linux-x86_644199097077208470722.so)

For context, this failure indicates that `libcrypt.so.1` was not found. Your operating system vendor will provide this. For example, on Fedora 24, `/lib64/libcrypt.so.1` is provided by the `glibc` package.

**Comment by jordansissel** [comment]
On my workstation at home, libnetty's tcnative library seems to link just fine for me:

```
% ldd ./META-INF/native/libnetty-tcnative-linux-x86_64.so
	linux-vdso.so.1 (0x00007ffc7694e000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff424c5c000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007ff424a24000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff424804000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff4245fc000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff424234000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007ff42402c000)
	/lib64/ld-linux-x86-64.so.2 (0x00005586c52c2000)
```

I hope this helps.
