### ISSUE TITLE
InsertingToQueueTakeTooLong

### ISSUE THREAD

**Issue by Sunde93** [logstash-plugins/logstash-input-beats#160]
I got this issue when i'm using filebeat as input : 

Multiline: flush downstream error {:exception=>#<LogStash::Inputs::Beats::InsertingToQueueTakeTooLong: LogStash::Inputs::Beats::InsertingToQueueTakeTooLong>, :level=>:error}

version : logstash-input-beats (2.2.9)
logstash-2.3.4

How can i avoid this ?

**Comment by ph** [comment]
@Sunde93 Can you update to logstash 5.0.0 or 2.4.1? both of theses version ship with a newer version of the beats input that has a newer implementation for communicating the back pressure back to the client?

Also concerning the multiline its better to do it closer to the source on the filebeat side.

**Comment by Sunde93** [comment]
Upgrading to logstash 2.4.1 correct my old issue, thanks.
