### ISSUE TITLE
client_inactivity_timeout is ignored and not effective

### ISSUE THREAD

**Issue by raja3000** [logstash-plugins/logstash-input-beats#168]
HI,

I am using v3.1.8 and noticed client_inactivity_timeout is ignored and not effective. I am using Ubuntu 14.04 

I have captured the same in our forum (discuss.elastic.co/c/logstash)

My configuration file

    input {
      beats {
        client_inactivity_timeout => 3000
        host => "192.168.57.4"
        port => 5044
      }
    }

**Comment by jordansissel** [comment]
@ph Thoughts?

**Comment by ph** [comment]
This was fixed in beats 3.1.10-12 with the PR #164 and #169, @raja3000 can you update to the latest version of the plugin? You can use the following command.

``bin/logstash-plugin update logstash-input-beats``

**Comment by daplho** [comment]
I'm sorry to report but I think this issue might be back - observing it right now on using a version 3.1.24 of logstash-input-filebeat and a version 5.6.0 of logstash. The `client_inactivity_timeout` is not set which means it ought to be 60 seconds thousands of connections are hanging out in `CLOSE_WAIT` state.

**Comment by jakelandis** [comment]
@daplho - can you try to update to the latest beats input, it has relevant changes
```
bin/logstash-plugin update logstash-input-beats
```

**Comment by daplho** [comment]
yes @jakelandis - I will give it a shot in a little bit and test it, then let you know back here if I've had success with it and the version that has enabled that success.

**Comment by daplho** [comment]
Update: I ran logstash version 5.6.8 with the logstash-input-beats plugin at version 3.1.30 for the last 48 hours in an integration environment and am happy to report that I did not see the `CLOSE_WAIT` issue during that time. Cheers!

**Comment by astateofmind01** [comment]
using latest logstash and latest beats input plugin apparently configuration option has been removed?

The server complains about  client_inactivity_timeout => 3000 directive as being unknown.

Was it changed?
