### ISSUE TITLE
Include Remote IP address in the Event medata

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-beats#180]
Currently, every event generated by the beats input contain the `beat.hostname` this information is copied from the original metadata sent by the client.  In some case it might be good to know the ip adress of the client to do better filtering.

I suggest we use the information on the connected client to add a new field named `beat.ip_address` that will hold the IP address

**Comment by jeanfabrice** [comment]
The use case you described is exactly the one I'm facing.

Shouldn't this ip be saved in the 'host' field to be consistant with what others (at least syslog, udp, tcp) inputs do ? 
What about this simple - not breaking - patch: https://github.com/jeanfabrice/logstash-input-beats/commit/eab2a8975aa73782ec095f0cd496023b3b3e0d29 ?

**Comment by jordansissel** [comment]
> the 'host' field to be consistant with what others (at least syslog, udp, tcp)

beats has numerous ways to provide identity information: custom fields, ssl certificate, etc, including this 'host' field.

Additionally, beats sends structured data, where tcp and udp do not. TCP input also [does not set the `host` field if it is already present](https://github.com/logstash-plugins/logstash-input-tcp/blob/master/lib/logstash/inputs/tcp.rb#L229) in the event -- for example, if you use  json codec with tcp and your json payload has a "host". This is  most similar to beats.

We can add the IP to metadata most easily, and from there if you want it as part of the event you could use mutate to move it. Thoughts?

**Comment by jeanfabrice** [comment]
Agree.
Feel free to add the ip in any beats structured field, we'll take care of it.

**Comment by MagnusMWW** [comment]
+1 to this. In a larger infrastructure it can be important to know where a particular message came from, and information provided by the client alone isn't always enough. Especially in cases where you control the reciever, but not the senders.

**Comment by Tester-Joe** [comment]
+1 as well. Having multiple beats from multiple machines pointing to one Logstash would be a good use-case for this. The ability to see where that beat is located by IP address would be a great addition.

**Comment by jakelandis** [comment]
@ph / @jordansissel - question on exactly where this should go ?

@ph - you mention ```beat.ip_address```
@jordansissel  - you referenced adding this to the metadata (assuming) ```@metatdata.ip_address```

Which is preferable ?

**Comment by jakelandis** [comment]
Spoke briefly with @ph and tentatively decided to target ```@metadata.ip_address``` as the home for this value. Hiding it abit, so that we don't accidentally break any ES mappings.  . _@jordansissel - please comment if you disagree._ 

Sample output (ruby codec with metaday)
```ruby
{
    "@timestamp" => 2017-06-07T20:12:50.671Z,
        "offset" => 0,
     "@metadata" => {
              "beat" => "filebeat",
        "ip_address" => "127.0.0.1",
              "type" => "log"
    },
      "@version" => "1",
    "input_type" => "stdin",
          "beat" => {
        "hostname" => "Jakes-MacBook-Pro.local",
            "name" => "Jakes-MacBook-Pro.local",
         "version" => "5.4.1"
    },
          "host" => "Jakes-MacBook-Pro.local",
        "source" => "",
       "message" => "testme",
          "type" => "log",
          "tags" => [
        [0] "beats_input_codec_plain_applied"
    ]
}
```

**Comment by johncollaros** [comment]
Which versions of logstash can we expect to see this feature in?
I am currently running 5.4.0 and need this feature.

**Comment by jakelandis** [comment]
@johncollaros - This will be bundled with the 6.0.0 release (which isn't released yet). 

However, the plugins have their own release schedule and this change has been released in the 4.0.3 version of this plugin. 

Assuming that you are NOT using multi-line codec in your beats input, you can upgrade to use the 4.0.3 plugin with this command:
```
bin/logstash-plugin install --version "4.0.3" logstash-input-beats
```
The full change log is here: https://github.com/logstash-plugins/logstash-input-beats/blob/master/CHANGELOG.md

Let me know if this will work for you. 

_note on 5.5+ you will also need to remove the pinned constraint from the Gemfile_

**Comment by johncollaros** [comment]
@jakelandis Thank you so much. I gave this a go and it is working using logstash-5.3.2.

**Comment by shijiebei2009** [comment]
@jakelandis @johncollaros 
I wonder to know can I use es 5.5.0 and filebeat 5.5.0 with logstash 6.0.0
because I want to output IP address to logstash too.
