### ISSUE TITLE
Maven repositories integration

### ISSUE THREAD

**Issue by fbacchella** [logstash-plugins/logstash-input-beats#183]
This code is a generic netty plugin. I tested it, it work flawless in about 20 lines of code, so it could be helpful to many peoples.

Can it be found in a public maven repository, so I can add it as a dependency to my pom.xml from my project ?

**Comment by ph** [comment]
Hi @fbacchella, We don't currently have a short them plan to make it available on maven central, we may revisit that in the future. But nothing prevent you to include the .jar in your project which will work.

previous discussion here: https://github.com/logstash-plugins/logstash-input-beats/issues/144
