### ISSUE TITLE
Issue with BeatsHandler.java

### ISSUE THREAD

**Issue by fbacchella** [logstash-plugins/logstash-input-beats#184]
Reading the code of the BeatsHandler, I see many things that I don't understand.

It's marked Sharable, but there is state in it, with the variables `processing` and `context`.

With:

    logger.debug("Sending a new message for the listener, sequence: " + message.getSequence());

A debug logger should not do operation without first checking if it's needed, especially when it's call frequently, like this one which is called for every message.

**Comment by ph** [comment]
Agree, I will change that.
