### ISSUE TITLE
Protocol version 1 can be improved

### ISSUE THREAD

**Issue by fbacchella** [logstash-plugins/logstash-input-beats#186]
For json payloed and compressed payload, reading the the header and the payload is separated in two steps. That allows decoding to works if the decode is called in the middle of the payload, it will just be called again.

This is not done for data field, the parsing is done in one pass, with incomplete payload, the decode will fail with out of bound exception, thrown by call like in.readBytes(fieldLength);

**Comment by ph** [comment]
@fbacchella The version 1 of the protocol is End of life, I don't see the need to support that anymore, In a future version of the beats we can remove it.
