### ISSUE TITLE
having issues with SSL options - what formats are allowed? 

### ISSUE THREAD

**Issue by paul42** [logstash-plugins/logstash-input-beats#197]
```
9:37:08.516 [nioEventLoopGroup-4-1] ERROR logstash.inputs.beats - Looks like you either have an invalid key or your private key was not in PKCS8 format. {:exception=>java.lang.IllegalArgumentException: File does not contain valid certificates: /etc/pki/tls/certs/{REDACTED}.der.crt}
```
why is it saying my key is invalid and then saying my cert file doesn't contain valid certificates? what forms are required for options (DER or PEM?)

**Comment by joelio** [comment]
I've had a similar issue when reusing puppet's CA infrastructure - it can be converted with something like

`openssl pkcs8 -topk8 -inform PEM -outform PEM -in {old}.pem -out {new}.pem -nocrypt`

**Comment by jstoja** [comment]
@jordansissel I'm currently struggling with the certificates as mentioned in the just linked issue on logstash-core.
I'm ready to help improving the documentation if I find a way to make it work with self signed, but for now, even when specifying my own CA cert, it fails complaining with the same error as described here...
I can reproduce by creating the cert and key with:
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout logstash.key -out logstash.crt
openssl pkcs8 -in logstash.key -topk8 -nocrypt -out logstash.p8
```
and
```
./bin/logstash -e "input {beats {port => 5000 ssl => true ssl_verify_mode => 'none' ssl_certificate => '/etc/ssl/logstash/logstash.crt' ssl_key => '/etc/ssl/logstash/logstash.p8' tags => ['beats']}}"
```
 
Any idea?

**Comment by jstoja** [comment]
Sorry for pushing, I'm sure many people also had issues like this and I think adding the solution to the doc will help! @ph ?

**Comment by jstoja** [comment]
I got confirmation from the code that pkcs8 is used by Netty's library:
https://github.com/logstash-plugins/logstash-input-beats/blob/2ac5d153a60899d1cab85135eba7f1495e7404a7/src/main/java/org/logstash/netty/SslSimpleBuilder.java#L110

This is the attached documentation that matches what I've done...

https://netty.io/wiki/sslcontextbuilder-and-private-key.html

**Comment by jordansissel** [comment]
@jstoja when I am doing lab testing/experiments, I use one command for generating my cert/key:

```
openssl req -x509  -batch -nodes -newkey rsa:2048 -keyout lumberjack.key -out lumberjack.crt -subj /CN=localhost
```

**Comment by jstoja** [comment]
@jordansissel How can this be compatible with Netty's requirement to have a key with PKCS8 format?

**Comment by jordansissel** [comment]
@jstoja I don't understand your question. The command I gave produces a certificate and private key that is usable for testing (again, this is how I test).

```
% openssl req -x509  -batch -nodes -newkey rsa:2048 -keyout lumberjack.key -out lumberjack.crt -subj /CN=localhost
Generating a 2048 bit RSA private key
........+++
..................+++
writing new private key to 'lumberjack.key'
-----
% bin/logstash -e 'input { beats { port => 12345 ssl_certificate => "lumberjack.crt" ssl_key => "lumberjack.key" ssl => true } }'
[2017-12-23T08:19:21,039][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.1.0"}
[2017-12-23T08:19:24,921][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>40, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>5000, :thread=>"#<Thread:0x75f6f4be run>"}
[2017-12-23T08:19:25,390][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:12345"}
[2017-12-23T08:19:25,480][INFO ][logstash.pipeline        ] Pipeline started {"pipeline.id"=>"main"}
...
```

The above demonstrates success with Logstash 6.1.0 and my one-liner key+cert generator (which I use for quick one-shot tests).

**Comment by jstoja** [comment]
Tested it and it works well. I'm a bit confused with the key formats required and how I generated my previous keypairs.
The only issue this test shows is the -e/-f option that cannot be used together and fail in some way.

Thank you very much for your answers, I'll use that from now on.

**Comment by peksilli** [comment]
@jstoja  "it was a very simple unix rights issue" - can you be more specific? Struggling with the same just now.

**Comment by peksilli** [comment]
OK. But if I understood right the solution above still doesn't provide mutual authentication, and the instructions in https://github.com/Busindre/How-to-configure-SSL-for-FileBeat-and-Logstash-step-by-step are at this point useless, right?

**Comment by sufiyanghori1** [comment]
Could it possibly be the same issue as https://github.com/spujadas/elk-docker/issues/112 ?

**Comment by nicolasbadia** [comment]
Did not manage to have a working certificate either. I tried a lot of thing but I always get this error: 

```
[2019-01-27T18:22:33,035][ERROR][logstash.inputs.beats    ] Looks like you either have a bad certificate, an invalid key or your private key was not in PKCS8 format.
[2019-01-27T18:22:33,049][WARN ][io.netty.channel.ChannelInitializer] Failed to initialize a channel. Closing: [id: 0xee63dcf5, L:/192.168.1.101:5400 - R:/145.239.69.82:45066]
java.lang.IllegalArgumentException: File does not contain valid private key: /etc/logstash/logstash.key
```

@jstoja can you tell me the permission you have on you certificate and private key. Mine is for root in 644 for .crt and 600 for .key. Also what do you mean when you say "the format of the keypair" ?

**Comment by jstoja** [comment]
Seems that adding debug logs would have helped (for the next ones) https://github.com/logstash-plugins/logstash-input-beats/blob/master/lib/logstash/inputs/beats/message_listener.rb#L65

**Comment by zayalaksme** [comment]
> Did not manage to have a working certificate either. I tried a lot of thing but I always get this error:
> 
> ```
> [2019-01-27T18:22:33,035][ERROR][logstash.inputs.beats    ] Looks like you either have a bad certificate, an invalid key or your private key was not in PKCS8 format.
> [2019-01-27T18:22:33,049][WARN ][io.netty.channel.ChannelInitializer] Failed to initialize a channel. Closing: [id: 0xee63dcf5, L:/192.168.1.101:5400 - R:/145.239.69.82:45066]
> java.lang.IllegalArgumentException: File does not contain valid private key: /etc/logstash/logstash.key
> ```
> 
> @jstoja can you tell me the permission you have on you certificate and private key. Mine is for `root` in `644` for `.crt` and `600` for` .key`. Also what do you mean when you say "the format of the keypair" ?
> 
> **Edit: found it! The user of the `.crt` and `.key` needs to be `logstash`, not `root`. The error message were not helping...**

chmod logstash:logstash *.key
chmod logstash:logstash *.pem

ITS WORKED FOR ME. FROM LAST 10 HOURS I AM ON THIS ISSUE. thANK YOU,

**Comment by jsvd** [comment]
https://github.com/logstash-plugins/logstash-input-beats/pull/394 has been created to distinguish between failure to read these files and unsupported/invalid key materials.
