### ISSUE TITLE
Add warning when using beats input with multiline when multiple hosts are configured

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-beats#199]
This is a high priority doc issue.

Here is the scenario:

* Beats is configured to have output.logstash output with multiple hosts in the hosts list.
* Logstash pipeline has a beats input with multiline codec in place to perform multiline processing.

The problem with the above setup is that if filebeat does not know about multiline (i.e. multiline is not configured via filebeat but as part of a LS input - this does not only apply to LS beats input, but any LS input that supports multiple hosts), it does not know which events belong together so it will happen that parts are sent to one host and other parts to an other host, causing a mixing of streams and corrupted event data generated.

Per @ruflin This is a known limitation and there isn't really a solution other than to configure multiline in beats instead of in Logstash.  

It is best if we can document this on both sides, not just in Beats documentation.  So this is the doc ticket for LS.  I will suggest calling this out in the managing multiline section (https://www.elastic.co/guide/en/logstash/current/multiline.html) and the codec configuration section (https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html#plugins-inputs-beats-codec).

Since this does not only affect the beats input, but other Logstash inputs that support multiple hosts, let's identify which ones they are and document accordingly.

**Comment by acchen97** [comment]
We've always recommended demuxing with multiline on the edge with Beats, so a big +1 on documenting this better. Things break when there's load balancing, but this should be a general recommendation regardless of whether LBing is involved.

@dedemorton I've added this to our [list](https://github.com/elastic/logstash/issues/6850). As this is across Beats and LS, do you mind helping with it?

Regarding other inputs like TCP and UDP, users do place a LB to distribute load across a fleet of LS nodes, but at that point it's really the job of the user to understand their data and demux it before shipping. I'm not sure if that's something we need to document in the plugin docs, but perhaps a general recommendation that lives in the deploying and scaling guide. /cc @jordansissel

**Comment by jordansissel** [comment]
I propose we instead have the beats input reject being configured with
multi line codec. We can have a failure message inform users to use multi
line in filebeat instead.

**Comment by dedemorton** [comment]
+1 to Jordan's suggestion. Although we should mention in the docs that LS mutliline should not be used with Filebeat, I worry that users won't see all the juicy tidbits like this that we sprinkle through the docs.

**Comment by jordansissel** [comment]
+1 also including some details in the beats input docs as well.

**Comment by acchen97** [comment]
@dedemorton following this morning's conversation, we can proceed with adding this messaging to the docs. Let's use a stronger statement than "recommend," as they really should never do it.

**Comment by dedemorton** [comment]
@acchen97 @ppf2 

I've created the following PRs to address this issue (and https://github.com/elastic/beats/issues/4008). Can you please review/approve. The ones marked off are already approved.

- [ ] https://github.com/logstash-plugins/logstash-codec-multiline/pull/52
- [ ] https://github.com/logstash-plugins/logstash-input-beats/pull/202
- [x] https://github.com/elastic/logstash/pull/6947 
- [ ] https://github.com/elastic/beats/pull/4086

**Comment by dedemorton** [comment]
This issue has been resolved in #202 (note that it won't show up in the published docs until the plugin docs are updated for the next release).
