### ISSUE TITLE
SslSimpleBuilder setProtocols ignored

### ISSUE THREAD

**Issue by swimmesberger** [logstash-plugins/logstash-input-beats#228]
There seems to be a issue in SslSimpleBuilder that you can't set the protocols because the local variable has the same name than the class property. Solutions would be to rename the local input variable or prefix the assignment class property with "this".
https://github.com/logstash-plugins/logstash-input-beats/blob/master/src/main/java/org/logstash/netty/SslSimpleBuilder.java#L69

Eclipse showed a warning when I checked the source.

**Comment by jakelandis** [comment]
@swimmesberger - Thanks for reporting this !
