### ISSUE TITLE
Correctly Handle the flush of the `IdentityMapcodec`

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-beats#23]
The `IdentityMapCodec` has an eviction mechanism that will flush unused codecs after 1 hour. The `encode` method of the codec need to receive a proc that can push to the queue. The current code base doesn't allow it since we use the encode method to return an event.

For more information see: https://github.com/logstash-plugins/logstash-input-beats/pull/22#issuecomment-
157449206

**Comment by ph** [comment]
There could be a small problem, this plugin use a custom sizequeue that support a timeout to apply back pressure to the client and make them disconnect, so the `encode` method will use that queue instead of using the normal one.

If the queue raise a timeout exception it will kill the eviction thread in the `IdentityMapCodec`, see https://github.com/logstash-plugins/logstash-codec-multiline/blob/master/lib/logstash/codecs/identity_map_codec.rb#L46

This is no happenning on normal queues because it will just block until we can write.

**Comment by ph** [comment]
@guyboertje any suggestion about the above problem?

**Comment by ph** [comment]
One way would be to be to define the cleanup callback on the identity map codec?
If not defined we use the one provided on the first decode?

**Comment by guyboertje** [comment]
@ph - sorry, I did not see your comment until now.

**Comment by ph** [comment]
depends on https://github.com/logstash-plugins/logstash-codec-multiline/issues/16

**Comment by ph** [comment]
This was implemented in the refactor of the plugin in #38
