### ISSUE TITLE
Sending events in lumberjack protocol to beats input

### ISSUE THREAD

**Issue by fmhwong** [logstash-plugins/logstash-input-beats#248]
Version:  Logstash 2.4.x and 5.x

We have a custom Java client that sends log events in lumberjack protocol to Logstash with lumberjack input.

```
input {
    lumberjack {
        port => "5043"
        ssl_certificate => "logstash.crt"
        ssl_key => "logstash.key"
    }
}
```
This has been working fine in Logstash 2.4.x and 5.x with IBM JDKs.  However, latest IBM JDK disabled an insecure cipher and the custom Java client cannot establish a SSL connection with Logstash anymore.  (I know IBM JDK is not on the supported list of JVMs.)  I was told that the lumberjack input is deprecated so we are looking for a migration path.  We changed the Logstash configuration to use beats input.

```
input {
    beats {
        port => "5043"
	ssl => true
        ssl_certificate => "logstash.crt" 
        ssl_key => "logstash.key" 
    }
}
```
The custom Java client was able to send log events to Logstash/Elasticsearch and view them in Kibana without any change. Do you know if this backward compatibility will continue to stay as is or will be changed in future?

**Comment by jakelandis** [comment]
I would assume that beats input interop with lumberjack has a future, since removing it would be very non-passive and believe that there may be some valid workflows which would require it's existence.  

@acchen97 / @suyograo  - Did you have any input here ?

**Comment by jordansissel** [comment]
At this time we have no plans to remove the v1 protocol (what the old lumberjack/logstash-forwarder used) support in the beats input.

Specific to your case, I want to caution you -- I do not consider the lumberjack protocol to be intended for other systems. The only supported clients are Elastic products and the only supported server is Logstash's beats input. Anything else is a kind of "good luck have fun" kind of scenario. We may be able to advise if something breaks, but our intent is, at least for now, provide a specific way for beats and logstash to communicate reliably.

**Comment by fmhwong** [comment]
Thanks for your responses!  I understand that Filebeat is the preferred log events shipper to Logstash.  However, Filebeat does not run on some of our required platforms such as AIX.  Our custom Java client remains the only option we have at this moment.

**Comment by jakelandis** [comment]
@fmhwong - closing issue.  Please re-open if there is more to discuss on this topic.
