### ISSUE TITLE
Copy beat.hostname into host

### ISSUE THREAD

**Issue by tsg** [logstash-plugins/logstash-input-beats#25]
The Beats are sending the hostname on which they run in the `beat.hostname` field. In Logstash, most input plugins are using the `host` field for this purpose. This is annoying for people that use Logstash with a lot of different sources.

After a bit of discussion on the topic, we decided that the best way forward would be to keep using `beat.hostname` in the Beats but have the logstash-input-beats plugin copy it to the `host` field.

**Comment by ph** [comment]
Make sense, we also use "host" as part of Event#to_s`

**Comment by nebularazer** [comment]
+1. just noticed that missing %{host} in my case (#24) today.

**Comment by urso** [comment]
@ph is there an official event schema? I thought only '@timestamp' and '@version' are somewhat mandatory. But I got the impression tags, type and host are kind of special too.

**Comment by ph** [comment]
@urso I can cook some documentation similar to what you have in beats? WDYT?

**Comment by urso** [comment]
@ph would be helpful. We've been just wondering about field assumptions in logstash (e.g. host being used in some places by default) as this is more or less the main concern about compatibility of events directly index from beat into elasticsearch and events index via logstash.

**Comment by jordansissel** [comment]
Fixed by #28

**Comment by nxhack** [comment]
sadly, it not work for me.
(logstash-input-beats-2.0.2, filebeat-1.0.0-rc2)
```
event["beat"]
```
is is defined?

https://github.com/logstash-plugins/logstash-input-beats/blob/master/lib/logstash/inputs/beats.rb#L159

**Comment by tsg** [comment]
@nxhack How did you install the new plugin? Maybe you are affected by #29?

**Comment by ph** [comment]
@nxhack can you do `bin/plugin list --verbose beats` and add the result here?

**Comment by nxhack** [comment]
@tsg @ph  As I posted, 
logstash-input-beats (2.0.2)
& filebeat-1.0.0-rc2

**Comment by nxhack** [comment]
````
  "_source": {
    "message": "2015-11-20T12:13:07.842354+09:00 xxxx sudo: pam_unix(sudo:session): session closed for user xxxx",
    "@version": "1",
    "@timestamp": "2015-11-20T03:13:07.842Z",
    "beat": {
      "hostname": "xxxx",
      "name": "xxxx"
    },
````
[beat][hostname] & [beat][name] was sent.

**Comment by nxhack** [comment]
I tried again, update logstash-input-beats 2.0.2 to 2.0.3, but result was not good.
dose it work? someone.

**Comment by ph** [comment]
@nxhack I am running beats input 2.0.3 with filebeat rc2 and my output contains the correct host field?

Can you post the content of the `Gemfile.jruby-1.9.lock` ?


```
{
    "@timestamp" => "2015-11-24T14:50:15.825Z",
       "message" => "2015-11-10 10:28:38,907 line 8\nline 8.1",
      "@version" => "1",
          "tags" => [
        [0] "multiline"
    ],
          "beat" => {
        "hostname" => "sashimi",
            "name" => "sashimi"
    },
         "count" => 1,
        "fields" => nil,
    "input_type" => "log",
        "offset" => 302,
        "source" => "/tmp/multi.log",
          "type" => "log",
          "host" => "sashimi"
}
```

**Comment by nxhack** [comment]
@ph 
[Gemfile.jruby-1.9.lock.txt](https://github.com/logstash-plugins/logstash-input-beats/files/43286/Gemfile.jruby-1.9.lock.txt)

OS: ubuntu 12.04.1
Java:  openjdk-7-jre 7u85-2.6.1-5ubuntu0
Logstash: logstash 1:2.0.0-1 & plugin update
ES: 2.0.0

**Comment by nxhack** [comment]
now LS 2.1.0 + logstash-input-beats (2.0.3) + filebeat 1.0.0 WORK FINE.
Thanks!
