### ISSUE TITLE
Add support for beat authentication via hostname regexps

### ISSUE THREAD

**Issue by pldiiw** [logstash-plugins/logstash-input-beats#265]
One of the limitations on the SSL side of this plugin is in its options on how to authenticate the Beats that connect to it.

Currently, the only way the input plugin provides to authenticate Beats is checking that the client certificate is signed by the configured CA.

Such a mean of authentication requires —_to my knowledge_ — you to manage your own CA.

Working with a "public" CA from which people that you don't trust can obtain a certificate would enable them to send logs to Logtash, as the Beats input plugin would verify this cert as a valid one as it has been signed by the same CA. 

If you want  to ensure that only the Beats instances you trust are sending you logs, and not undesired ones, you will have to face to tedious process of setting your own PKI infrastructure with root CA, intermediate CAs and on and on. For little project, it is clearly overwhelming. And automating it is even more overwhelming.

The ability to use entities like Let's Encrypt to issue SAN certificates for our Beats would enable a simpler and easier workflow for early projects and tinkering.

One way, to authenticate Beats using certificates from such CAs would be to, _firstly_, __verify that the Beat host name matches the one written on the certificate__ (if it doesn't already accomplish it as of today — I don't know as it isn't written in the [guide] that such a check exists). And _secondly_, __to add a setting that would validate that the CN on the certificate__ (verified, as previously) __belongs to a subdomain/matches against a list of names.__

We can imagine something like a `client_regex` setting that takes a regular expression when matched, indicates the Beat client is one of ours:

```ruby
input {
    beat {
        ...
        client_regex => /.*\.beats\.elastic\.co/
        ...
    }
}
```

Again, it is aimed to better integrate with servers already using LE certs, for instance.

[guide]: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html

**Comment by nick-george** [comment]
Would you be comfortable with some form of secure token based authentication (as described in #266)?

**Comment by ypid-geberit** [comment]
@pldiiw

Lets Encrypt does not issue client certificates as of now. So you would probably end up with your own CA for that anyway unless you want to pay some CA for doing that.

The good news is that the input now exposes the `tls_subject_cn` so Logstash is not the limiting factor anymore. This issue can be closed I would say.

https://github.com/logstash-plugins/logstash-input-beats/issues/83

**Comment by pldiiw** [comment]
Sorry for the looong time.

@nick-george, you proposal fills the need, as the end goal is to offer an alternative authentication mean to the classic PKI. Security-wise, SSL certificates are ultra-safe, but for small scale infrastructures and restricted team sizes, it might be too much of a burden, sadly. Your token-based authentication proposal would totally be enough for such use cases.

@ypid-geberit Yes, at the time I thought it more as a lever to aid early setup. The need for a self-managed CA showing up quickly anyway. The new `ssl_peer_metadata` option is neat. To be honest, I'm near no setup where I can test what it exposes and the documentation is not very thorough about it, but it seems to, indirectly, exactly bring what I was asking for. Thanks for the notice about it, I'm closing the issue as it is resolved.
