### ISSUE TITLE
[docs] Document requirements for SSL mutual authentication

### ISSUE THREAD

**Issue by inqueue** [logstash-plugins/logstash-input-beats#298]
Version 6.1.

Documentation at https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html should outline the requirements for SSL mutual authentication when SSL is desired. Attempting to configure the Beats input plugin without mutual authentication results in error:

```
[2018-02-13T12:00:30,391][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: undefined] Exception: javax.net.ssl.SSLHandshakeException: error:100000c0:SSL routines:OPENSSL_internal:PEER_DID_NOT_RETURN_A_CERTIFICATE
```

`ssl_verify_mode` also appears to not have any impact on SSL mutual authentication. Is this setting still valid?

**Comment by jordansissel** [comment]
Mutual authentication is not required. Can you attach your configuration?

**Comment by inqueue** [comment]
The real [issue](https://github.com/logstash-plugins/logstash-input-beats/issues/300) was uncovered. Closing this one.
