### ISSUE TITLE
SSL client authentication enabled when certificate_authorities is configured

### ISSUE THREAD

**Issue by inqueue** [logstash-plugins/logstash-input-beats#300]
Logstash version 6.1

After talking to @ph, Beats input is enabling client certificate verification if `certificate_authorities` is configured. 

Logstash logs an error if Beats is not configured for authentication:
```
[2018-02-14T12:33:04,478][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, 
remote: undefined] Exception: javax.net.ssl.SSLHandshakeException: error:100000c0:SSL 
routines:OPENSSL_internal:PEER_DID_NOT_RETURN_A_CERTIFICATE
```

Setting `ssl_verify` to `none` has no impact. The workaround is to not set `certificate_authorities` or configure Beats for client authentication. 

https://gist.github.com/inqueue/0370eab746082a797700673b75ffa0bd has a configuration that reproduces the error.

**Comment by jordansissel** [comment]
@inqueue what is your expectation of behavior?

The act of setting `certificate_authorities` should be an expression by the user/operator that they *want* to only accept trusted clients. Maybe we need to improve the wording/docs here?

Alternately, why would you set `ssl_verify => none` *and* also set `certificate_authorities` ? Why would you say "Trust the things  in `certificate_authorities`" but then tell the plugin to ignore trust relationships? What's the use case and intent?

**Comment by jordansissel** [comment]
To clarify, I agree it's a bit confusing, and I think we can improve by setting expectations. I also agree that the behavior today seems correct -- honestly I'm not sure I understand why a user would want `ssl_verify => none` while also setting `certificate_authorities` so I want to understand more.

**Comment by inqueue** [comment]
Thanks @jordansissel. This was based on the _false_ assumption the plugin requires `certificate_authorities` for SSL to be setup correctly-- a point clearly addressed in the [docs](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html#plugins-inputs-beats-ssl_certificate_authorities) for the parameter. This was a bug of confusion, closing it out.

**Comment by jordansissel** [comment]
@inqueue TLS/SSL is super confusing. I think a lot about how we can improve the experience. Thanks for filling this :)

**Comment by berlic** [comment]
OMG. An hour of debugging... The docs should stress in bold that `ssl_verify_mode => none` has no effect if `ssl_certificate_authorities` is set.

@inqueue my situation: I've copied server configuration from production server to dev server and just disabled `ssl_verify_mode` without deleting `ssl_certificate_authorities` line.

**Comment by karenzone** [comment]
@karenzone  ^^ Opportunities to improve docs
