### ISSUE TITLE
Date conversion

### ISSUE THREAD

**Issue by iammichiel** [logstash-plugins/logstash-input-beats#32]
Hello, 

I'm trying to run a basic sample with file tailing in filebeat and simply forwarding to logstash. However, I have the following error when logstash receives the message :

    The field '@timestamp' must be a (LogStash::Timestamp, not a String (2015-11-23T10:49:43.423Z)>,

What is going wrong here? Is it the plugin? Is it the filebeat configuration? 
Thanks !

Running : 
> logstash-input-beats (0.9.2)

**Comment by ruflin** [comment]
@iammichiel You must update to the most recent version of logstash-input-beats 0.9.6:

https://www.elastic.co/guide/en/beats/libbeat/1.0.0-rc2/getting-started.html#logstash-input-update

**Comment by iammichiel** [comment]
Hi, 

Thanks for the quick answer. Indeed, updating solved the problem ! :)
