### ISSUE TITLE
netty-beans publishing to maven.

### ISSUE THREAD

**Issue by fbacchella** [logstash-plugins/logstash-input-beats#325]
Hi,
I have started to extract the netty-beans components from the the plugin and plan to publish it to maven.
The github repo can be found at https://github.com/fbacchella/netty-beats.
I have also tested it on [Sonarcloud](https://sonarcloud.io/dashboard?id=LogHub%3Anetty-beats) and published a binary on [Bintray](https://bintray.com/fbacchella/maven/netty-beats).
Sonarcloud help me spot some weakness in the code, so I have already commit a few patches beside prepare the setup.
I'm using maven because I know it better, but that's just for the sake of simplicity.
I'm open to any request from your side, and hope we can collaborate on this.

**Comment by jakelandis** [comment]
@fbacchella - What is the motivation for packaging this as a standalone jar ?  

> I'm open to any request from your side, and hope we can collaborate on this.

Forks generally have a hard time keeping this in sync with any changes upstream (and vice-versa).  I doubt that we would be able to help maintain a fork, but PR's here are always welcome.  I am curious of other uses cases outside of Logstash that this approach may solve.

**Comment by fbacchella** [comment]
I know that an hard fork are not a good solution. But it's much more that a PR from logstash-input-beats. So I will be more that happy to give you back my projet, and it should be setup as a separated project from both my code and logstash's plugin. But if you have other proposition, we can discus it.
I wrote it because I'm not a big fan of logstash and ruby, so I rewrote it with 100% java heavily optimised code, and a DSL using antlr: https://github.com/fbacchella/LogHub. It's also using netty for the network stack, so using the netty's part is interesting for me.

**Comment by fbacchella** [comment]
Done: https://repo1.maven.org/maven2/fr/loghub/netty-beats/1.0.0-RC1/

**Comment by kares** [comment]
2 years later it seems to be still stuck at 1.0.0 RC2, anyhow I am closing this one due inactivity.

**Comment by fbacchella** [comment]
I have just committed code that add check against DOS, there is almost no input sanitising in the current version. And I have checked all of the ByteBuf leaks during tests. One was coming from Message.
