### ISSUE TITLE
zlib buffer errors

### ISSUE THREAD

**Issue by jlintz** [logstash-plugins/logstash-input-beats#34]
```
{:timestamp=>"2015-12-08T17:20:11.966000-0500", :message=>"Beats input: unhandled exception", :exception=>#<Zlib::BufError: buffer error>, :backtrace=>["org/jruby/ext/zlib/ZStream.java:134:in `finish'", "org/jruby/ext/zlib/JZlibInflate.java:72:in `inflate'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:292:in `compressed_payload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:163:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:296:in `compressed_payload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:163:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/lumberjack/beats/server.rb:342:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/lumberjack/beats/server.rb:319:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.0.3/lib/logstash/inputs/beats.rb:184:in `invoke'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.2-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_1486431032.gen:13:in `run'"], :level=>:error}
```

Seem to be getting this continuously on some nginx logs

Input is just

```
    beats {
      port               => 12348
      codec              => json
    }
```

And the nginx logs are JSON formatted.  I'll see if I can create a reproducible case

Versions:
logstash 2.1.0-1
logstash-input-beats (2.0.3)
filebeat 1.0.0

**Comment by ph** [comment]
@jlintz Thanks! if you can get a lot that would be awesome! @urso Any ideas?

**Comment by urso** [comment]
@jilints can you try to reduce the bulk size? Maybe set to very low values (like 50 or 100) and see this still happens.

@ph no idea, but looks like an older problem: logstash-plugins/logstash-input-lumberjack#9 .
I kinda feel tricked by jruby stack trace and branch naming. Which [branch](https://github.com/jruby/jruby) do I have to look at? Looking at master for [buffer error](https://github.com/jruby/jruby/search?utf8=%E2%9C%93&q=newBufError). It seems we might get this error if buffer is [either empty](https://github.com/jruby/jruby/blob/3c164ca93d1e60373fd5f2c7f1895915fb8c577e/core/src/main/java/org/jruby/ext/zlib/JZlibInflate.java#L235) or some [whatever error is returned] (https://github.com/jruby/jruby/blob/3c164ca93d1e60373fd5f2c7f1895915fb8c577e/core/src/main/java/org/jruby/ext/zlib/JZlibInflate.java#L274). Unfortunately you can not distinguish these two. Beats does [check if at least 1 event has been compressed](https://github.com/elastic/beats/blob/master/libbeat/outputs/logstash/client.go#L107) before sending, but we do not check the actual buffer size of compressed data (we should). The lumberjack also does [not check the expected buffer size](https://github.com/elastic/ruby-lumberjack/blob/master/lib/lumberjack/server.rb#L287). In case length == 0, we should transition to head (and maybe print some info log?). Adding buffer size checks we can at least rule out some issues.

**Comment by ph** [comment]
@urso agree that would rule out some issues to have theses checks.

Good finding about jruby, I usually look for the master branch all the time.

**Comment by jlintz** [comment]
@urso do you mean the spool size in filebeat?

**Comment by urso** [comment]
@jlintz no. the bulk_max_size in LS output module: https://www.elastic.co/guide/en/beats/libbeat/current/configuration.html#_bulk_max_size

The spool will be forwarded to outputer and LS outputer will slice it into multiple batches.

**Comment by jlintz** [comment]
@urso it looks like bulk_max_size is for ES output module only according to the docs you linked

**Comment by urso** [comment]
@jlintz seems to be a doc bug (can you fill a ticket?). The [init code](https://github.com/elastic/beats/blob/master/libbeat/outputs/logstash/logstash.go#L70) is reading this config value.

**Comment by jlintz** [comment]
Changing bulk_max_size to 25 seems to have fixed the issue

**Comment by ph** [comment]
I will be closing this issue this problem was related to the old implementation of beats done in ruby. I believe the current java implementation is not affected by this issue.
