### ISSUE TITLE
High Number of TCP Resets from Logstash Beats Plugin

### ISSUE THREAD

**Issue by sparky005** [logstash-plugins/logstash-input-beats#355]
We have a couple ec2 instances running Logstash configured behind an AWS Network Load Balancer. The Network load balancer periodically connects to each logstash listener in order to verify that it is up and running. After deploying a new logstash configuration and enabling the Beats input plugin, we noticed that the number of TCP RST packets being sent from the logstash nodes increased tenfold.

It looks like the beats input plugin is closing the TCP conversation with the load balancer with a TCP RESET instead of sending a FIN (see images for comparison.)

Does anybody know why this is happening? Is this a bug in the logstash beats plugin or is this expected behavior? Note that this behavior does not happen with a normal TCP listener.

Bad:
<img width="1279" alt="bad" src="https://user-images.githubusercontent.com/5643040/49904240-96b68300-fe37-11e8-8159-5212ae8fa3ad.png">
Good:
<img width="1277" alt="good" src="https://user-images.githubusercontent.com/5643040/49904243-9918dd00-fe37-11e8-9455-31f0cfae6dde.png">

- Version: logstash: 6.5.3, plugin: 5.1.8
- Operating System: centos7
- Config File (if you have sensitive info, please remove it):
input:
```
input {
  tcp {
    port => 5000
    codec => json
  }
  beats {
    port => 5001
    tags => ["dba"]
  }

}
```
filters:
```
filter {
  if "dba" in [tags] {
    date {
      match => [ "[msg][asctime]", "yyyy-MM-dd HH:mm:ss,SSS" ]
    }
  }

}
```
output
```
output {
  if "dba" in [tags] {
    amazon_es {
      hosts => ["censored"]
      region => "us-east-1"
      index => "dba-%{+YYYY.MM.dd}"
    }
  } else {
    amazon_es {
      hosts => ["censored"]
      region => "us-east-1"
      index => "%{type}-%{+YYYY.MM.dd}"
    }
  }

}
```
- Sample Data: n/a
- Steps to Reproduce: Set up some logstash ec2 instances with a beats listener behind a Network Load Balancer in AWS.

**Comment by troal** [comment]
Hi, 
I have the same problem also behind an AWS Network Load Balancer.
Version: logstash: 6.7.2, plugin: 5.1.8
Operating System: Amazon Linux 2

Have you managed to solve it?

**Comment by sparky005** [comment]
@troal sadly, I have not.

**Comment by sparky005** [comment]
Closing this, I don't even work at the place that I was having this issue at anymore lol
