### ISSUE TITLE
Add proxy TCP header to metadata

### ISSUE THREAD

**Issue by jeffrey-e** [logstash-plugins/logstash-input-beats#374]
I am trying to use SSL/TLS offloading at Nginx. As we use client authentication and check the CN for a specific value, it would be great if I can add the CN to a proxy header and read it with the beats input in Logstash. I could not find any option for this.

- Version: 7.4.2
- Operating System: Debian Stretch

**Comment by gekkeharry13** [comment]
Found this method. I am not familiar with java, so I am struggling a bit to create a test case on my own.
https://netty.io/4.1/api/io/netty/handler/codec/Headers.html
If someone can assist met in adding all headers or just a specific one to the metadata then I can test it first and create a PR after successful tests.
Thanks in advance
