### ISSUE TITLE
unhandled exception Broken Pipe

### ISSUE THREAD

**Issue by BrianKITHEN** [logstash-plugins/logstash-input-beats#5]
Hello,
I'm testing the master branch of PacketBeat with Logstash 1.5.4. When there is only one instance of PacketBeat running, everything is fine. However, when multiple instances are running and feeding Logstash, I often get the following error. Also, documents are missing in ElasticSearch.

```Beats input: unhandled exception {:exception=>#<Errno::EPIPE: Broken pipe - Broken pipe>, :backtrace=>["org/jruby/RubyIO.java:1334:in `syswrite'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:379:in `send_ack'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:362:in `ack_if_needed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:345:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:246:in `json_data_payload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:163:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:296:in `compressed_payload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:163:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:330:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:315:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/logstash/inputs/beats.rb:150:in `invoke'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.1-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_2076907911.gen:13:in `run'"], :level=>:error}```

**Comment by urso** [comment]
Hi BrianKITHEN,

have you seen any errors logged by packetbeat? Can you run packetbeat with debug selectors:
-d 'publish,logstash' ?

**Comment by urso** [comment]
@BrianKITHEN can you try to used most recent master from packetbeat and update logstash-input-beats plugin in logstash?

Thanks for testing!!!

**Comment by urso** [comment]
@BrianKITHEN can you try to increase the connection timeout in packetbeat (https://github.com/elastic/libbeat/blob/master/docs/configuration.asciidoc#logstash-output)? The default timeout is 30 (in seconds).

**Comment by BrianKITHEN** [comment]
@urso I raised the timeout and memory usage for Logstash and ES. Doesn't change.
Debug selector 'logstash' doesn't print anything. Packetbeat binary displays version beta4 though.

I'm trying to integrate PCAP files to ES through Logstash. I think the throughput might be too high for Logstash (but it worked for ES). When I reduce the number of running instances, there isn't any problem. The issue might be because Packetbeat's takes longer to empty its buffer. For the moment there is no feature to make sure Packetbeats's buffer is empty before it exits.
I will keep using -waitstop with a reduce number of Packetbeat instances.

**Comment by urso** [comment]
@ph you have an idea?

@BrianKITHEN what you use logstash for? How many ES nodes do you have? packetbeat also supports loadbalancing to multiple logstash instances if that's an option.

**Comment by ph** [comment]
@urso I'll take a look

**Comment by ph** [comment]
@BrianKITHEN Can you share your configuration? What OS/JVM are you running?

**Comment by ph** [comment]
@BrianKITHEN Any errors in the beat logs?

**Comment by BrianKITHEN** [comment]
I'm really sorry for not answering you; I wasn't on github for some time.
Logstash is used to remove many fields from the PacketBeat output and to drop some packets. ES had only 1 node.

I'm running PacketBeat on Debian. There wasn't any error in the beat logs.

I'll be testing the plugin again this week.

**Comment by urso** [comment]
@BrianKITHEN for very simple filtering use cases you might want to follow elastic/libbeat#111

**Comment by BrianKITHEN** [comment]
Thanks @urso . That would be really nice feature.
