### ISSUE TITLE
Beats input blocked

### ISSUE THREAD

**Issue by cdenneen** [logstash-plugins/logstash-input-beats#57]
```
{:timestamp=>"2016-03-10T18:09:00.402000-0500", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Beats input", :exception=>LogStash::Inputs::Beats::InsertingToQueueTakeTooLong, :level=>:war
n}
{:timestamp=>"2016-03-10T18:09:00.408000-0500", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Beats input", :exception=>LogStash::Inputs::Beats::InsertingToQueueTakeTooLong, :level=>:war
n}
{:timestamp=>"2016-03-10T18:09:00.413000-0500", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecti
ng new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
{:timestamp=>"2016-03-10T18:09:00.408000-0500", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Beats input", :exception=>LogStash::Inputs::Beats::InsertingToQueueTakeTooLong, :level=>:war
n}
{:timestamp=>"2016-03-10T18:09:00.415000-0500", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecti
ng new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
{:timestamp=>"2016-03-10T18:09:00.417000-0500", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecti
ng new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
{:timestamp=>"2016-03-10T18:09:00.425000-0500", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Beats input", :exception=>LogStash::Inputs::Beats::InsertingToQueueTakeTooLong, :level=>:war
n}
{:timestamp=>"2016-03-10T18:09:00.427000-0500", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecti
ng new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
{:timestamp=>"2016-03-10T18:09:06.457000-0500", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Beats input", :exception=>LogStash::Inputs::Beats::InsertingToQueueTakeTooLong, :level=>:war
n}
{:timestamp=>"2016-03-10T18:09:06.459000-0500", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecti
ng new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
{:timestamp=>"2016-03-10T18:09:07.448000-0500", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Beats input", :exception=>LogStash::Inputs::Beats::InsertingToQueueTakeTooLong, :level=>:war
n}
{:timestamp=>"2016-03-10T18:09:07.450000-0500", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecti
ng new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
{:timestamp=>"2016-03-10T18:09:07.451000-0500", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Beats input", :exception=>LogStash::Inputs::Beats::InsertingToQueueTakeTooLong, :level=>:war
n}
{:timestamp=>"2016-03-10T18:09:07.453000-0500", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecti
ng new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
{:timestamp=>"2016-03-10T18:09:08.453000-0500", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn}
{:timestamp=>"2016-03-10T18:09:08.484000-0500", :message=>"CircuitBreaker::Open", :name=>"Beats input", :level=>:warn}
{:timestamp=>"2016-03-10T18:09:08.486000-0500", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecti
ng new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::OpenBreaker, :level=>:warn}
...
{:timestamp=>"2016-03-10T18:09:55.256000-0500", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn}
{:timestamp=>"2016-03-10T18:09:55.757000-0500", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn}
{:timestamp=>"2016-03-10T18:09:55.780000-0500", :message=>"The error reported is: \n  execution expired"}
```
```
input {
  beats {
    # The port to listen on
    port => 9001
    tags => ['beats']
  }
}
```

logstash 2.2.2
logstash-input-beats 2.1.4

**Comment by ph** [comment]
@cdenneen What outputs are you using? I am wondering where "{:timestamp=>"2016-03-10T18:09:55.780000-0500", :message=>"The error reported is: \n  execution expired"}" is coming from.

**Comment by ph** [comment]
This issue is related to this other one you have create https://github.com/logstash-plugins/logstash-output-sqs/issues/9 ?

If one of the output is blocking the pipeline the beats input will effectively block and reject new events/connection this is the expected behavior.

**Comment by cdenneen** [comment]
@ph 2 different instances one with beats input has ES output...

**Comment by cdenneen** [comment]
yeah I'm curious where this is too... ```The error reported is: \n execution expired``` this is probably what's blocking the pipeline... I just don't know where it is

**Comment by ph** [comment]
@cdenneen OK than is not related, can you share your config?

**Comment by ph** [comment]
I did a quick search in  for "The error reported is" on the 2.2.2 code base and I can't find something related to the error you are getting. Can you reproduce it easily? if so adding `--debug` when starting logstash would give us where this error is emitted. This is far from ideal, but this would help us localize the log statement.

I suspect this is some kind of timer and/or a mutex timeout?

**Comment by cdenneen** [comment]
@ph this is similar to issue I had with es output and `workers => "12"` caused crash while `workers => 12` didn't.
I think update to the --configtest is a must for logstash.
I'm trying to find the String issue that's causing this but I think based  on my 2 issues it's something to do with output-sqs on one instance and input-sqs on the other (all latest)

**Comment by jordansissel** [comment]
> workers => "12" caused crash while workers => 12 didn't.

This sounds like an unrelated (and unexpected?) issue. The `workers` setting is [declared a number](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/outputs/base.rb#L26), and the [validation code for number](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/config/mixin.rb#L448-L468) hasn't changed in about [3 years[(https://github.com/elastic/logstash/blame/master/logstash-core/lib/logstash/config/mixin.rb#L448-L468). If you experience a problem with respect to `"12"` vs `12` in the elasticsearch output, then it could be a bug, but not something wrong with the beats input plugin.

**Comment by cdenneen** [comment]
@jordansissel yes it's unrelated to beats but similar to the \n issue above. 
"12" worked in 2.1.1 but not in 2.2.2 so it might not have been mixin but something changed that didn't like this. 
All I was suggesting in related to the other String related parsing error was possibly a way to improve the overall config test. I can open a bug in logstash.

**Comment by ph** [comment]
Yup that code didnt change, the only thing that change related to worker is that we now use delegators for the output. But this shouldn't cause any problems on the string vs number in the configuration since the coercion is done in the mixin.

**Comment by cdenneen** [comment]
Still not sure why the String issue (\n) is happening but my blocked input beats was because of sqs output issues as result of underlying issue on ESXi node. Closing as my issue for beats directly is now resolved.

**Comment by ph** [comment]
Thanks @cdenneen for updating this!
My guess concerning the `execution expired", I think its coming from the AWS library IIRC they have check when an execution takes too long to completed. Still worth investigating and making this error more clear.
