### ISSUE TITLE
beats_input_codec_json_applied being added to tags

### ISSUE THREAD

**Issue by briangruber** [logstash-plugins/logstash-input-beats#58]
I have json strings being written to a log file, one per line and I'm using filebeats to ship off to logstash (doing this instead of the logstash input plugin because that seemed to miss lines randomly and filebeats doesn't)

Here is the basic config for the input in logstash

```
input {
  beats {
    codec => "json"
    host => "127.0.0.1"
    port => 5044
  }
}
```

My json object has a "tags" property that we use already and it seems that the beats input plugin adds `beats_input_codec_json_applied` to the tags property. I've had to right a filter to remove that tag (which also slows down logstash unnecessarily)

Is there any way it can avoid adding that tag to the object?

**Comment by briangruber** [comment]
It appears to be adding all kinds of keys to my object and OVERWRITING any existing ones. Is there any way to just stop it from adding anything at all? I don't need to store any of this in elasticsearch.

**Comment by ph** [comment]
> I have json strings being written to a log file, one per line and I'm using filebeats to ship off to logstash (doing this instead of the logstash input plugin because that seemed to miss lines randomly and filebeats doesn't)

Did you create an issue for that? I presume it was with the file input?

> My json object has a "tags" property that we use already and it seems that the beats input plugin adds beats_input_codec_json_applied to the tags property. I've had to right a filter to remove that tag (which also slows down logstash unnecessarily) Is there any way it can avoid adding that tag to the object?

I can see it as an option for disabling the tagging? I have added this since not only filebeat can send events logstash but topbeat, etc and it was a bit hard to know for a user when the codec was actually applied to the event.

**Comment by ph** [comment]
> It appears to be adding all kinds of keys to my object and OVERWRITING any existing ones. Is there any way to just stop it from adding anything at all? I don't need to store any of this in elasticsearch.

Would you mind adding to this issue your json document and the json output that logstash produce?

**Comment by roidelapluie** [comment]
This behaviour is annyoing.  It breaks backward compat with the lumberjack input.

**Comment by ph** [comment]
@roidelapluie @briangruber Would you be in favor of adding an option to remove this behavior? I think its only a problem when the original data is coming from a json document?

**Comment by dvsekhvalnov** [comment]
+1 If `tag` property was generate by application, filebeat overwrites it with content of shipper.tags section + `beats_input_codec_json_applied` value.

It should be merged IMO. because it doesn't allow app to use dynamic tagging of events.

**Comment by sigmavirus24** [comment]
This seems related to #96.

I would love to have a configuration option to disable this instead of having to add it to a filter to remove these.
