### ISSUE TITLE
SSL_key_passphrase doesn't currently work.

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-beats#61]
Discovered when debugging an issue in https://github.com/logstash-plugins/logstash-input-tcp/issues/48
We need to call `.value` here to make sure we have the right key to decrypt the private key

https://github.com/logstash-plugins/logstash-input-beats/blob/master/lib/logstash/inputs/beats.rb#L118

**Comment by Ihjaz** [comment]
Hi,

I have the following configuration now with ssl_key_passphrase.

```
input {
  beats {
    host => "10.129.179.39"
    port => 5044
    ssl => true
    ssl_certificate => "/etc/logstash/certs/first-cert.pem"
    ssl_key => "/etc/logstash/certs/enc_key.p8"
    ssl_key_passphrase => "admin"
  }
```
I have encrypted key.p8 as follows with 'admin' as key phrase.

> openssl rsa -aes256 -in key.p8 -out enc_key.p8

But with the encrypted key file and passphrase configured, I am seeing the following error in logstash logs.

> [2017-09-14T21:57:05,709][ERROR][logstash.inputs.beats ] Looks like you either have an invalid key or your private key was not in PKCS8 format.

I'm running logstash 5.5.1.

**Comment by jakommo** [comment]
I hit this as well:
```
[2017-11-23T15:14:04,906][ERROR][logstash.inputs.beats    ] Looks like you either have an invalid key or your private key was not in PKCS8 format. {:exception=>java.lang.IllegalArgumentException: File does not contain valid private key: /home/ec2-user/20171123/cert-key.pkcs8}
```
the `pkcs8`  file actually does not even have a passhrase and it's working fine as soon as I remove the `ssl_key_passphrase => ...` from my config. 

@ph mind having another look?
