### ISSUE TITLE
SSL chain certificates

### ISSUE THREAD

**Issue by danielgblanco** [logstash-plugins/logstash-input-beats#64]
Chained certificates don't seem to be working for `beats` input. I have the following configuration:

```
  beats {
    port => 5044
    ssl => true
    ssl_certificate => "/path/to/my/certificate.crt"
    ssl_key => "/path/to/my/certificate.key"
  }
```

The `certificate.crt` file has a chain of certificates, but the intermediate ones don't appear to be sent correctly, because an `openssl s_client -host myhost -port 5044 -prexit -showcerts` fails to verify the first certificate in the chain.

If I do the same with the `tcp` input, it just works:

```
  tcp {
    port => 5044
    ssl_enable => true
    ssl_cert => "/path/to/my/certificate.crt"
    ssl_key => "/path/to/my/certificate.key"
    ssl_extra_chain_certs => "/path/to/my/certificate.crt"
  }
```

Any idea how to proceed? Thanks

**Comment by suyograo** [comment]
@danielgblanco chained certs don't work currently because of an underlying jruby bug. we're looking into it: https://github.com/jruby/jruby-openssl/issues/84

**Comment by danielgblanco** [comment]
Okay thank you. I'll stay tuned :)

**Comment by JNachtwey** [comment]
+ 1 Is there a workaround for this jruby bug?

**Comment by danielgblanco** [comment]
One possible workaround is to add the chained certificate to the list of certificate authorities in your FileBeat conf (e.g. `/etc/filebeat/filebeat.yml`) in the following way:

```
output:
    logstash:
        tls:
            certificate_authorities : ["/path/to/your/chained.crt"]
```

**Comment by JNachtwey** [comment]
I tested the workaround. It´s not working with chained certificates.

**Comment by lenrico** [comment]
https://www.elastic.co/guide/en/beats/filebeat/current/configuring-tls-logstash.html

> Although intermediate CAs are currently not supported, you may be able to work around this issue by merging all the certificates in the chain into one file. You can create the PEM file containing the CA chain by concatenating the root CA cert and the intermediate CA into a single file: cat root-ca.crt intermediate-ca.crt > chain.crt. Then set certificate_authorities to use this file: certificate_authorities: ['chain.crt'].

**Comment by lenrico** [comment]
Hi,

any updates here?

The workaround is ok, but not THE solution.
We need a trusted chain to validate all clients, a secure connection alone is not sufficient.

Is that issue not important enough?

Can we help with anything, tests or something else then let us know!?


Best
Enrico

**Comment by ph** [comment]
@lenrico Would you mind testing logstash alpha5, there is a new version of the beats input which should support intermediate CA.

**Comment by lenrico** [comment]
I,ll do some tests and give you feedback...

**Comment by ph** [comment]
I will be closing this, since the java rewrite certificate chains now works and we have integration test for that scenario.
