### ISSUE TITLE
TCP connections not being closed causes FD leak

### ISSUE THREAD

**Issue by robin13** [logstash-plugins/logstash-input-beats#74]
As there is not (currently) a keepalive signal from beats or a timeout in beats, connections remain indefinitely open leading to a filedescriptor leak - over time a logstash agent running with the logstash-input-beats may have thousands of open TCP connections, eventually running against the system limit for filedescriptors.

**Comment by kurt5** [comment]
+1

**Comment by jordansissel** [comment]
@robin13 ahh, if the connection is opened by beats (client) and then abandoned (due to network failure or other disappearing-act) the TCP connection never closes? 

+1 on adding a heartbeat frame to the beats protocol.

**Comment by robin13** [comment]
@jordansissel Yes - that's it.

**Comment by ph** [comment]
This is fixed in the java rewrite, the settings is very high for now 750 seconds, but I will reduce that to 30 and expose it in the plugin.
