### ISSUE TITLE
Verify client certificates against CA

### ISSUE THREAD

**Issue by andrenarchy** [logstash-plugins/logstash-input-beats#8]
Currently, the beats input does not verify the client certificate against the CA. This means that *any* client can connect to *any* logstash server and submit arbitrary data. Besides cluttering the logstash server with meaningless data, attackers could try to take servers down by submitting huge amounts of data.

Analogous to [filebeat](https://github.com/elastic/filebeat)/[logstash-forwarder](https://github.com/elastic/logstash-forwarder), the client certificate should be checked against the CA on the server side.

See also logstash-plugins/logstash-input-lumberjack#31.

**Comment by klj613** [comment]
+1

**Comment by AndreasWurm** [comment]
indeed, stumbled over this too. In Filebeat you can set the accepted CAs and cipher suites.
The same should be true for the receiving end.

**Comment by bobelev** [comment]
+1

**Comment by runningman84** [comment]
This seems to be an important issue, if you want to drop lumberjack in the future you should at least have the same kind of security with beats.

Funny enough filebeat already supports using a client certificate. Logstash filebeat input just fails to validate it.

Please add this option:
```
ssl_client_cert_check
```

**Comment by jordansissel** [comment]
@runningman84 I don't think the lumberjack input does validation (on the logstash input side) of client certificates - the original threat model was to protect data leaks (so lsf doesn't ship to untrusted servers). There's been enough requests for client authentication via certificate that it's worth adding this feature, so  I agree. Hope the background helps.

**Comment by acchen97** [comment]
+1 on implementing this, /cc @suyograo

**Comment by filipemarinheiro** [comment]
+1 For me this is a major security fault and should be implemented as soon as possible

**Comment by ravi412** [comment]
+1 . We are planning a large-scale install of filebeat on 1000+ machines hence this is a critical feature.

**Comment by ph** [comment]
I am starting to look at this following the use cases defined in https://github.com/logstash-plugins/logstash-input-lumberjack/issues/31

**Comment by rjes** [comment]
+1
Since we would like to send log from instances in iaas/paas locations where we can't setup ip-filters this feature is very crucial for us.

**Comment by acchen97** [comment]
Thanks for the feedback, we're targeting this within a short-term release.

**Comment by erikswanson** [comment]
When this gets implemented, can we please have access to information about the client certificate? I want to be able to an event to what client certificate was used to send it to Logstash.

**Comment by ph** [comment]
> When this gets implemented, can we please have access to information about the client certificate? I want to be able to trace an event to what client certificate was used to send it to Logstash.

The event already contains the information about the shippe (which should be similar from the certificate)? Is that enough? What is your use case here?

**Comment by erikswanson** [comment]
> The event already contains the information about the shippe (which should be similar from the certificate)? Is that enough? What is your use case here?

I need attribution of events to shippers to be absolute under the assumption of a malicious or compromised shipper. Hence, ideally, a logstash rule that puts information about the verified client ceritificate into the event instead of trusting origin information put into the event itself by the shipper.

**Comment by ph** [comment]
When implementing this I have encountered a Jruby/OpenSSL bug thats blocking me and that prevent the server to use intermediate ca. I have created an issue on Jruby-OpenSSL to track this https://github.com/jruby/jruby-openssl/issues/84

#56 is incomplete because of that, it will only work if the CA sign the client certificate directly which is problematic when you want to isolate CA.

**Comment by ph** [comment]
I would like to have your feedback here concerning the usage of this feature, The PR #56 implement and currently work when you have a `Root CA` that directly sign Client/Server is this what you have in your current setup or you have a `Root Ca` and an `intermediate CA` that sign the Client and server certificate?

Is this an acceptable solution for you? I don't have a workaround until the jruby-openssl bug is fixed

**Comment by darvid** [comment]
any workaround for the fact that you can't use client certs signed by a root + intermediary? looks like jruby/jruby-openssl#84 has been open for over a year now...
